### ISSUE TITLE
where is the VM?

### ISSUE THREAD

**Issue by jessewriter** [gunnarx/webex-box#2]
I ran your script and it took forever but I don't see a virtualbox instance anywhere in the folder...

also there is a desktop file that is created that goes to your webex page not sure if you intended to do that

**Comment by gunnarx** [comment]
@jessewriter 

> I ran your script and it took forever but I don't see a virtualbox instance anywhere in the folder...

On my machine the VM instance ends up in the default folder for VirtualBox which is something like 
"~/VirtualBox VMs", unless you have changed it with a setting.  I don't think about the location much because it is registered to VirtualBox and can be seen if you open the VirtualBox GUI.  There's usually a VM left behind even if something is unsuccessful in provisioning, but you can check status with:

```
$ vagrant status
```

 [Vagrant documentation](https://www.vagrantup.com/) might give more information on how this works and what to expect.

> ... it took forever ...

... was that meant as some kind of criticism? :-)  Happy to hear any proposals you might have.

> also there is a desktop file that is created that goes to your webex page not sure if you intended to do that.  

Well sure, that was intentional.  The project was set up for "our" usage in [GENIVI](https://github.com/GENIVI) but it's interesting that others find it.  So the Desktop shortcut was a good convenience for us.   Now a few months later, the master branch will be Zoom only, since that's what we use now so I should remove that and it will no longer be an issue for anyone else.  (Feel free to fork)
